name: Lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    name: Lint with Ruff and Mypy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff mypy
        pip install numpy xarray scipy matplotlib

    - name: Run Ruff
      run: |
        ruff check SlocumBatteryPercentageDuration.py

    - name: Run Mypy
      run: |
        mypy SlocumBatteryPercentageDuration.py --install-types --non-interactive
